`timescale 1ns/1ps

module dac39j84_physical_mapper (
    input  wire [63:0] dac_out0,
    input  wire [63:0] dac_out1,
    input  wire [63:0] dac_out2,
    input  wire [63:0] dac_out3,
    input  wire [3:0]  map_mode,
    output wire [63:0] converter0,
    output wire [63:0] converter1,
    output wire [63:0] converter2,
    output wire [63:0] converter3
);

    // Public contract:
    //   dac_out0..3 are the user-visible physical DAC output streams.
    //   Each stream is four chronological 16-bit samples, sample0 in [15:0].
    //
    // This module is only the hidden preimage between those physical streams
    // and the generated LiteJESD converter-bus interface. The byte placement
    // follows the Sundance DAC sample adapter pattern for the current board:
    //
    //   output 0: high lane 3, low lane 0
    //   output 1: high lane 2, low lane 1
    //   output 2: high lane 7, low lane 6
    //   output 3: high lane 5, low lane 4
    //
    // map_mode is retained only for diagnostics. Normal operation is 4'd0.

    genvar i;
    generate
        for (i = 0; i < 4; i = i + 1) begin : gen_sample
            wire [15:0] src0 = dac_out0[(16*i) +: 16];
            wire [15:0] src1 = dac_out1[(16*i) +: 16];
            wire [15:0] src2 = dac_out2[(16*i) +: 16];
            wire [15:0] src3 = dac_out3[(16*i) +: 16];

            reg [15:0] cand_a;
            reg [15:0] cand_b;
            reg [15:0] cand_c;
            reg [15:0] cand_d;
            reg [7:0]  j0;
            reg [7:0]  j1;
            reg [7:0]  j2;
            reg [7:0]  j3;
            reg [7:0]  j4;
            reg [7:0]  j5;
            reg [7:0]  j6;
            reg [7:0]  j7;

            always @(*) begin
                case (map_mode[1:0])
                2'd1: begin
                    // Reverse candidate order. This is only for connector-label
                    // discovery; do not use it as a byte-order fix.
                    cand_a = src3;
                    cand_b = src2;
                    cand_c = src1;
                    cand_d = src0;
                end
                2'd2: begin
                    // Swap the first candidate pair for diagnostics.
                    cand_a = src1;
                    cand_b = src0;
                    cand_c = src2;
                    cand_d = src3;
                end
                2'd3: begin
                    // Swap the upper candidate pair for diagnostics.
                    cand_a = src0;
                    cand_b = src1;
                    cand_c = src3;
                    cand_d = src2;
                end
                default: begin
                    // Default contract: physical DAC output N uses dac_outN.
                    cand_a = src0;
                    cand_b = src1;
                    cand_c = src2;
                    cand_d = src3;
                end
                endcase

                // Default lane-pair preimage into LiteJESD logical byte lanes:
                //   candidate A: high J3, low J0
                //   candidate B: high J2, low J1
                //   candidate C: high J7, low J6
                //   candidate D: high J5, low J4
                //
                // J0..J7 are the logical JESD byte lanes generated by
                // litejesd_dac_tx after it splits converter0..3 into adjacent
                // high/low byte lanes. The assignments below build the
                // converter-bus preimage for that generated lane splitter.
                j0 = cand_a[7:0];
                j1 = cand_b[7:0];
                j2 = cand_b[15:8];
                j3 = cand_a[15:8];
                j4 = cand_d[7:0];
                j5 = cand_d[15:8];
                j6 = cand_c[7:0];
                j7 = cand_c[15:8];

                case (map_mode[3:2])
                2'd1: begin
                    // Verify the upper-pair orientation:
                    //   candidate C: high J6, low J7
                    //   candidate D: high J4, low J5
                    j4 = cand_d[15:8];
                    j5 = cand_d[7:0];
                    j6 = cand_c[15:8];
                    j7 = cand_c[7:0];
                end
                2'd2: begin
                    // Verify the lower-pair orientation:
                    //   candidate A: high J0, low J3
                    //   candidate B: high J1, low J2
                    j0 = cand_a[15:8];
                    j1 = cand_b[15:8];
                    j2 = cand_b[7:0];
                    j3 = cand_a[7:0];
                end
                2'd3: begin
                    // Full byte-orientation diagnostic.
                    j0 = cand_a[15:8];
                    j1 = cand_b[15:8];
                    j2 = cand_b[7:0];
                    j3 = cand_a[7:0];
                    j4 = cand_d[15:8];
                    j5 = cand_d[7:0];
                    j6 = cand_c[15:8];
                    j7 = cand_c[7:0];
                end
                default: begin
                    // Keep the default expected lane-pair preimage.
                end
                endcase
            end

            // LiteJESD converter0 emits logical lane0=high byte and
            // logical lane1=low byte; converter1 emits lanes 2/3, etc.
            assign converter0[(16*i) +: 16] = {j0, j1};
            assign converter1[(16*i) +: 16] = {j2, j3};
            assign converter2[(16*i) +: 16] = {j4, j5};
            assign converter3[(16*i) +: 16] = {j6, j7};
        end
    endgenerate

endmodule
