# ZCU102 Rev 1.x FMC HPC0/J5 launch constraints for FMC-ADC500-CD / SE120 board-health test
# JESD data-lane placement is owned by the generated GTH Wizard XCI. This file
# covers sideband, SPI, fabric-sampled clocks, SYSREF, and MGT reference clocks.
#
# ZCU102 HPC0 note:
# - VADJ_FMC_PGOOD is generated by board regulator U63 and reaches FMC D1.
# - PG_M2C is pulled up on the carrier.
# - PRSNT_M2C_B/JTAG bypass handling is through board logic / I2C expander,
#   not a simple PL pin. These signals are therefore not constrained here.

# HMC7044 CLK_FMC -> FMC CLK0_M2C
set_property PACKAGE_PIN AA7 [get_ports FMC1_HPC_CLK0_M2C_P]
set_property PACKAGE_PIN AA6 [get_ports FMC1_HPC_CLK0_M2C_N]
set_property IOSTANDARD LVDS [get_ports {FMC1_HPC_CLK0_M2C_P FMC1_HPC_CLK0_M2C_N}]
set_property DIFF_TERM TRUE [get_ports {FMC1_HPC_CLK0_M2C_P FMC1_HPC_CLK0_M2C_N}]
create_clock -name DAQ_CLK_FMC -period 10.000 [get_ports FMC1_HPC_CLK0_M2C_P]

# HMC7044 SYSREF_FMC -> LA00_CC
set_property PACKAGE_PIN Y4 [get_ports DAQ_SYSREF_P]
set_property PACKAGE_PIN Y3 [get_ports DAQ_SYSREF_N]
set_property IOSTANDARD LVDS [get_ports {DAQ_SYSREF_P DAQ_SYSREF_N}]
set_property DIFF_TERM TRUE [get_ports {DAQ_SYSREF_P DAQ_SYSREF_N}]

# DAC_SYNC -> LA01_CC
set_property PACKAGE_PIN AB4 [get_ports DAC_SYNC_P]
set_property PACKAGE_PIN AC4 [get_ports DAC_SYNC_N]
set_property IOSTANDARD LVDS [get_ports {DAC_SYNC_P DAC_SYNC_N}]
set_property DIFF_TERM TRUE [get_ports {DAC_SYNC_P DAC_SYNC_N}]

# DAC39J84 SPI / sideband pins
# DAC_SCLK  -> LA02_P
# DAC_SDIN  -> LA02_N
# DAC_SDOUT -> LA03_P
# DAC_CS_N  -> LA04_N
# DAC_TXEN  -> LA04_P
# DAC_RESET -> LA07_P, active-low in this launch design
# DAC_ALARM -> LA07_N
set_property PACKAGE_PIN V2 [get_ports DAC_SCLK]
set_property PACKAGE_PIN V1 [get_ports DAC_SDIN]
set_property PACKAGE_PIN Y2 [get_ports DAC_SDOUT]
set_property PACKAGE_PIN AA1 [get_ports DAC_CS_N]
set_property PACKAGE_PIN AA2 [get_ports DAC_TXEN]
set_property PACKAGE_PIN U5 [get_ports DAC_RESET_N]
set_property PACKAGE_PIN U4 [get_ports DAC_ALARM]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SCLK DAC_SDIN DAC_SDOUT DAC_CS_N DAC_TXEN DAC_RESET_N DAC_ALARM}]

# ADC resets kept controllable but deasserted by default.
# ADC1_RESET -> LA03_N
# ADC2_RESET -> LA05_N
set_property PACKAGE_PIN Y1 [get_ports ADC1_RESET]
set_property PACKAGE_PIN AC3 [get_ports ADC2_RESET]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC1_RESET ADC2_RESET}]

# HMC7044 SPI / reset pins
# HMC_CLK_RESET -> LA13_N
# HMC_CLK_SDIO  -> LA14_P
# HMC_CLK_SCLK  -> LA14_N
# HMC_CLK_CS_N  -> LA15_P
set_property PACKAGE_PIN AC8 [get_ports HMC_CLK_RESET]
set_property PACKAGE_PIN AC7 [get_ports HMC_CLK_SDIO]
set_property PACKAGE_PIN AC6 [get_ports HMC_CLK_SCLK]
set_property PACKAGE_PIN Y10 [get_ports HMC_CLK_CS_N]
set_property IOSTANDARD LVCMOS18 [get_ports {HMC_CLK_RESET HMC_CLK_SDIO HMC_CLK_SCLK HMC_CLK_CS_N}]

# FMC MGT reference clocks. The ODIV2 outputs are sampled by the 200 MHz fabric
# monitor; they are not promoted into BUFG_GT resources. The optional GTH health
# build also feeds the IBUFDS_GTE4 O outputs into the wizard.
set_property PACKAGE_PIN G8 [get_ports FMC1_HPC_GBTCLK0_M2C_C_P]
set_property PACKAGE_PIN G7 [get_ports FMC1_HPC_GBTCLK0_M2C_C_N]
create_clock -name DAQ_GBTCLK0 -period 8.000 [get_ports FMC1_HPC_GBTCLK0_M2C_C_P]

set_property PACKAGE_PIN L8 [get_ports FMC1_HPC_GBTCLK1_M2C_C_P]
set_property PACKAGE_PIN L7 [get_ports FMC1_HPC_GBTCLK1_M2C_C_N]
create_clock -name DAQ_GBTCLK1 -period 8.000 [get_ports FMC1_HPC_GBTCLK1_M2C_C_P]
